" Configuration

set nocompatible              " be iMproved, required
filetype off                  " required
set rnu
set expandtab
set shiftwidth=2
set softtabstop=2
set nu
set autoread
set number
" Mappings

map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>

map <Esc><Esc> :q <CR>

map <F2> :NERDTreeToggle <CR>
map <F3> :Ag 
map <F4> :Rake <CR>
map <F5> :w <CR>
map ` :Gstatus <CR>
map <F8> Ibinding.pry<CR><Esc><F5>
map <F9> Idebugger;<CR><Esc><F5>
map <F10> Isave_and_open_page<CR><Esc><F5>
map <Space> /
map ñ :
map <Tab> $
map <C-z> :Emodel 
map <C-c> :Econtroller  
map ' :vs<CR>
map ; :sp<CR>
map 0 :Gd<CR>

imap <F5> <Esc><F5>
imap <F9> <Esc><F9>
" Move between windows
nmap <C-Left> <C-W>h
nmap <C-Down> <C-W>j
nmap <C-Up> <C-W>k
nmap <C-Right> <C-W>l

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

" Plugins
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
" Good looking bottom :)
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'kien/ctrlp.vim'
Plugin 'slim-template/vim-slim'
Plugin 'vim-ruby/vim-ruby'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-fugitive'
Plugin 'thoughtbot/vim-rspec'
Plugin 'tpope/vim-rails'
Plugin 'scrooloose/syntastic'
" Plugin 'ervandew/supertab'
Plugin 'SirVer/ultisnips'
Plugin 'kchmck/vim-coffee-script'
Plugin 'oplatek/Conque-Shell'
Plugin 'pangloss/vim-javascript'

"theme
Plugin 'tomasr/molokai'
call vundle#end()            " required

" Snippets config
let g:rspec_command='!bin/rspec {spec}'
let g:syntastic_ruby_checkers = ['rubocop']
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<S-tab>"
"put snips on dotfile folder
"let g:UltiSnipsSnippetsDir="~/.dotfiles/vim/snips"
" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

"comment unless pathogen installed
execute pathogen#infect()

filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
" filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Configs to make Molokai look great
set background=dark
let g:molokai_original=1
let g:rehash256=1
set t_Co=256
colorscheme molokai
" Show trailing whitespace and spaces before a tab:
:highlight ExtraWhitespace ctermbg=red guibg=red
:autocmd Syntax * syn match ExtraWhitespace /\s\+$\| \+\ze\\t/
" Lovely linenumbers
set nu

let g:airline_theme='luna'
let g:airline_powerline_fonts=1
set laststatus=2

set runtimepath^=~/.vim/bundle/ag
let g:ag_working_path_mode="r"
set runtimepath^=~/.vim/bundle/ag
